# This script defines a function called `strict_content` which is used for content moderation.
# The function checks if any blocked words are present in the given content and returns True if any are found.
# This is useful for filtering out inappropriate or harmful content in user-generated inputs. ReliaChat AI Innovations, IS NOT RESPONSIBLE FOR ANY WARRNTY
# OR MISUSE ON THE SOFTWARE. THE SOFTWARE IS PROVIDED AS IS. FOR MORE INFO GO TO: https://github.com/LTS-VVE/ReliaChat/blob/main/LICENSE, TO VIEW THE LICENSE.

def strict_content(content):
    # Blocked Words.
    # NOTE THAT THIS SECTION OR FILE OF CODE IS SIMPLY FOR MODERATION, AND ReliaChat AI Innovations IS NOT PROMOTING, ADVERTISING, OR HAVING RELIABILITY
    # FOR ANY OF THE WORDS, PROVIDED FOR MODERATION.
    blocked_words = [
        "rape", "kill", "murder", "suicide", "pedophilia", "child exploitation", 
        "child pornography", "terrorism", "extremist", "bomb", "weapon", "assault", 
        "abuse", "violence", "gore", "torture", "slavery", "genocide", "incest", 
        "bestiality", "necrophilia", "cannibalism", "snuff film", "human trafficking", 
        "child abuse", "child molestation", "child sexual abuse", "child sexual exploitation", 
        "child pornography material", "child sexual assault", "child grooming", "child abduction", 
        "child rape", "child prostitution", "child trafficking", "child slavery", "child labor", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "child labor slavery", "child labor abuse", "child labor violation", "child labor exploitation", 
        "child labor trafficking", "child labor slavery", "child labor abuse", "child labor violation", 
        "child labor exploitation", "child labor trafficking", "child labor slavery", "child labor abuse", 
        "child labor violation", "child labor exploitation", "child labor trafficking", "child labor slavery", 
        "child labor abuse", "child labor violation", "child labor exploitation", "child labor trafficking", 
        "faggots", "faggot", "anti-gay", "anti gay", "Anti Lgbtqia+", "Anti Agenda LGBTQ+", "Anti LGBT", "Fuck faggots",
        "die faggots", "die child", "How to terrorise children?", "How to build bomb", "how to fuck an animal", "fucking animals", "anti lgbt", "child labor",
        "dhunim", "vrasje", "vrasje", "vetëvrasje", "pedofili", "shfrytëzim i fëmijëve",
        "pornografi fëmijësh", "terrorizëm", "ekstremist", "bombë", "armë", "sulm",
        "abuzim", "dhunë", "krim", "torturë", "skllavëri", "gjenocid", "incest",
        "bestialitet", "nekrofilia", "kanibalizëm", "film snuff", "trafikimi i qenieve njerëzore",
        "abuzim i fëmijëve", "ngacmim i fëmijëve", "abuzim seksual i fëmijëve", "shfrytëzim seksual i fëmijëve",
        "materiale pornografike fëmijësh", "sulm seksual i fëmijëve", "ngacmim i fëmijëve", "rrëmbim i fëmijëve",
        "dhunim i fëmijëve", "prostitucion i fëmijëve", "trafikim i fëmijëve", "skllavëri e fëmijëve", "punë e fëmijëve",
        "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve",
        "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve",
        "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve",
        "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve",
        "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve",
        "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve",
        "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve",
        "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve",
        "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve",
        "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve",
        "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve",
        "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve",
        "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve",
        "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve",
        "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve",
        "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve",
        "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve",
        "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve",
        "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve", "shfrytëzim i punës së fëmijëve",
        "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve", "shkelje e punës së fëmijëve",
        "shfrytëzim i punës së fëmijëve", "trafikim i punës së fëmijëve", "skllavëri e punës së fëmijëve", "abuzim i punës së fëmijëve",
        "shkelje e punës së fëmijëve", "anti-gej", "anti homoseksualeve", "si te vras", "abuzimi mendor", "eating disorder", "eation disorders",
        "anti gej",
    ]
    
    # Currently there only is 2 langauges for profanity check. Please view our READ.ME on github or gitlab for more info.


    # Check if any blocked word is in the content
    for word in blocked_words:
        if word in content.lower():
            return True
    
    return False
